title: Robert Ridgway
logo: /assets/img/logo.png
description: Hi! I'm a Postgraduate Researcher at the University of Exeter. My research is in Exoplanets, in particular the effects of stellar flares on the habitability of terrestrial planets orbiting M Dwarfs.
google_analytics:
theme: jekyll-theme-minimal
