title: Robert Ridgway
logo: /assets/img/CanoeLogo.jpg
description: Exoplanet climatologist, number cruncher, and lover of physics
long_description: Hi! I'm a physicist who has recently completed a PhD in Physics at the University of Exeter. My research was in Exoplanets, in particular the effects of stellar flares on the habitability of terrestrial planets orbiting M Dwarfs. I am interested in planetary science, data analysis, and exoplanets.
google_analytics:
theme: jekyll-theme-minimal
